// Generated by CoffeeScript 1.3.3

define(["../button_bar/AbstractButtonBarView", "common/Math2"], function(AbstractButtonBarView, Math2) {
  var buttonBarOptions;
  buttonBarOptions = {
    x: function(e) {
      var val;
      val = parseFloat(e.target.value);
      if (!isNaN(val)) {
        return this.model.changeSlidePosition(val);
      }
    },
    y: function(e) {
      var val;
      val = parseFloat(e.target.value);
      if (!isNaN(val)) {
        return this.model.changeSlidePosition(null, val);
      }
    },
    z: function(e) {
      var val;
      val = parseFloat(e.target.value);
      if (!isNaN(val)) {
        return this.model.changeSlidePosition(null, null, val);
      }
    },
    rotateX: function(e) {
      var val;
      val = parseFloat(e.target.value);
      if (!isNaN(val)) {
        return this.model.changeSlideRotations(val);
      }
    },
    rotateY: function(e) {
      var val;
      val = parseFloat(e.target.value);
      if (!isNaN(val)) {
        return this.model.changeSlideRotations(null, val);
      }
    },
    rotateZ: function(e) {
      var val;
      val = parseFloat(e.target.value);
      if (!isNaN(val)) {
        return this.model.changeSlideRotations(null, null, val);
      }
    },
    slideEditor: function(e) {
      return this.$el.trigger("changePerspective", {
        perspective: "slideEditor"
      });
    },
    preview: function(e) {
      return this.$el.trigger("preview");
    },
    lookDownZ: function(e) {},
    lookDownY: function(e) {},
    lookDownX: function(e) {}
  };
  return AbstractButtonBarView.extend({
    events: function() {
      return {
        "keyup *[data-option]": "optionChosen",
        "paste *[data-option]": "optionChosen",
        "click .btn[data-option]": "optionChosen",
        "click": "clicked"
      };
    },
    initialize: function() {
      AbstractButtonBarView.prototype.initialize.call(this, buttonBarOptions);
      this.model.on("change:slidePosition", this._slidePositionChanged, this);
      return this.model.on("change:slideRotations", this._slideRotationsChanged, this);
    },
    _slidePositionChanged: function(model, slidePosition) {
      return this.partialRender(slidePosition);
    },
    _slideRotationsChanged: function(model, slideRotations) {
      return this.partialRender(null, slideRotations);
    },
    clicked: function(e) {
      e.stopPropagation();
      return false;
    },
    partialRender: function(slidePosition, slideRotations, sceneRotations) {
      slidePosition || (slidePosition = this.model.slidePosition());
      if (slidePosition != null) {
        this.updatePositionControls(this.$slidePosCtrls, slidePosition);
      }
      slideRotations || (slideRotations = this.model.slideRotations());
      if (slideRotations != null) {
        return this.updateRotationControls(this.$slideRotCtrls, slideRotations);
      }
    },
    updatePositionControls: function($which, position) {
      return $which.each(function(idx, elem) {
        var val;
        val = position[idx];
        if (!(val != null) || isNaN(val)) {
          val = 0;
        }
        return $(elem).val(val);
      });
    },
    updateRotationControls: function($which, rotations) {
      return $which.each(function(idx, elem) {
        var val;
        val = rotations[idx];
        if (!(val != null) || isNaN(val)) {
          val = 0;
        }
        return $(elem).val(Math2.round(val, 2));
      });
    },
    render: function() {
      this.$slidePosCtrls = this.$el.find(".slidePosition input");
      this.$slideRotCtrls = this.$el.find(".slideRotations input");
      return this.partialRender();
    }
  });
});
